# Generated by Django 4.2a1 on 2023-02-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('secondname', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('pass1', models.CharField(max_length=12)),
            ],
        ),
    ]
