# Generated by Django 4.2a1 on 2023-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('pass1', models.CharField(max_length=12)),
            ],
        ),
    ]
