# Generated by Django 4.2a1 on 2023-02-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0002_model_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model_1',
            new_name='Model1',
        ),
        migrations.RenameModel(
            old_name='Model_2',
            new_name='Model2',
        ),
    ]
