# Generated by Django 4.2a1 on 2023-02-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0004_model3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100)),
                ('youremail', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=150)),
                ('yourmessage', models.TextField()),
            ],
        ),
    ]
