# Generated by Django 4.2a1 on 2023-02-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contactus',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Massege',
            new_name='Message',
        ),
    ]
