# Generated by Django 4.2a1 on 2023-02-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0002_rename_contact_contactus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pTitle', models.CharField(max_length=50)),
                ('pDesc', models.CharField(max_length=200)),
                ('pImages', models.ImageField(upload_to='')),
                ('pPrice', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
