# Generated by Django 4.2a1 on 2023-02-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0004_addprouct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addprouct',
            new_name='addproduct',
        ),
    ]
