# Generated by Django 4.2a1 on 2023-02-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0006_register_user_delete_addproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USER',
            new_name='LOGIN',
        ),
    ]
