# Generated by Django 4.2a1 on 2023-02-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0007_rename_user_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='REGISTER',
        ),
    ]
