# Generated by Django 4.2a1 on 2023-03-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work',
            field=models.TextField(blank=True),
        ),
    ]
