# Generated by Django 4.2a1 on 2023-03-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0011_userprofile_education_userprofile_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
