# Generated by Django 4.2a1 on 2023-03-02 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beautifile', '0012_register_profile_image_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='register',
            name='uname',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
