# Generated by Django 4.2a1 on 2023-03-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0013_remove_register_profile_image_register_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='uname',
            field=models.CharField(max_length=100),
        ),
    ]
