# Generated by Django 4.2a1 on 2023-03-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0016_alter_register_profile_image_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
