# Generated by Django 4.2a1 on 2023-03-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0018_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
