# Generated by Django 4.2a1 on 2023-03-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0019_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
