# Generated by Django 4.2a1 on 2023-03-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0022_profile_dob_profile_mobile_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PRODUCTS',
            new_name='Product',
        ),
    ]
