# Generated by Django 4.2a1 on 2023-03-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0028_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uname',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
