# Generated by Django 4.2a1 on 2023-03-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0031_rename_uname_register_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='user',
            new_name='uname',
        ),
    ]
