# Generated by Django 4.2a1 on 2023-03-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0035_profile_email_profile_mobile_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
