# Generated by Django 4.2a1 on 2023-03-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0036_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='login',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='login',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='login',
            name='uname',
        ),
    ]
