# Generated by Django 4.2a1 on 2023-03-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0038_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
