# Generated by Django 4.2a1 on 2023-03-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0040_userdetails_remove_session_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images.png', null=True, upload_to='images/'),
        ),
    ]
