# Generated by Django 4.2a1 on 2023-03-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0041_userdetails_username_alter_userdetails_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='username',
            new_name='User',
        ),
    ]
