# Generated by Django 4.2a1 on 2023-03-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0044_linkgenerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkgenerate',
            name='user_id',
        ),
    ]
