# Generated by Django 4.2a1 on 2023-03-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0045_remove_linkgenerate_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkgenerate',
            name='link_id',
            field=models.CharField(auto_created=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='linkgenerate',
            name='token',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
