# Generated by Django 4.2a1 on 2023-03-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0048_remove_linkgenerate_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkgenerate',
            name='expiry',
            field=models.CharField(default='s', max_length=500),
        ),
    ]
