# Generated by Django 4.2a1 on 2023-03-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0049_alter_linkgenerate_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='update',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='repassword',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
