# Generated by Django 4.2a1 on 2023-03-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0050_register_update_alter_register_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='register',
            name='repassword',
            field=models.CharField(max_length=12),
        ),
    ]
