# Generated by Django 4.2a1 on 2023-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0051_alter_register_password_alter_register_repassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AddField(
            model_name='register',
            name='user_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='uname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
