# Generated by Django 4.2a1 on 2023-03-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautifile', '0052_remove_register_id_register_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
