# Generated by Django 4.2a1 on 2023-02-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0002_rename_password_userregister_pass1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='pass1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='pass2',
            new_name='repassword',
        ),
    ]
