# Generated by Django 4.2a1 on 2023-02-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0003_delete_userlogin_rename_pass1_userregister_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='first_name',
            new_name='user_name',
        ),
    ]
