# Generated by Django 4.2a1 on 2023-02-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0004_rename_first_name_userregister_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='password',
            new_name='password1',
        ),
    ]
