# Generated by Django 4.2a1 on 2023-02-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0005_rename_password_userregister_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='repassword',
        ),
    ]
