# Generated by Django 4.2a1 on 2023-02-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0006_remove_userregister_repassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='second_name',
            new_name='secondname',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='user_name',
            new_name='username',
        ),
    ]
