# Generated by Django 4.2a1 on 2023-02-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_log_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up',
            name='pass2',
        ),
    ]
