# Generated by Django 4.2a1 on 2023-04-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=12)),
                ('pass2', models.CharField(max_length=12)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
