# Generated by Django 4.2a1 on 2023-04-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='profile_image',
            new_name='prof_img',
        ),
    ]
