# Generated by Django 4.2a1 on 2023-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_profile_image_signup_prof_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('Yourname', models.CharField(max_length=100)),
                ('Yourmail', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
            ],
        ),
    ]
