# Generated by Django 4.2a1 on 2023-04-13 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_signup_created_at_signup_is_delete_signup_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userprof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crud.signup')),
                ('username', models.CharField(max_length=50, null=True)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='images.png', null=True, upload_to='images/')),
            ],
        ),
    ]
