# Generated by Django 4.2a1 on 2023-04-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_userprofile_is_delete_userprofile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='firstname',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
