# Generated by Django 4.2a1 on 2023-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_signup_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='firstname',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
