# Generated by Django 4.2a1 on 2023-04-14 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_userprofile_userprof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userprof',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crud.signup'),
        ),
    ]
