# Generated by Django 4.2a1 on 2023-04-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_alter_userprofile_userprof'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=12)),
                ('pass2', models.CharField(max_length=12)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('prof_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userprof',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
