# Generated by Django 4.2a1 on 2023-04-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_user_remove_userprofile_userprof_delete_signup_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
