# Generated by Django 4.2a1 on 2023-04-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_user_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
