# Generated by Django 4.2a1 on 2023-04-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='prof_img',
            field=models.ImageField(blank=True, default='images.png', null=True, upload_to='images/'),
        ),
    ]
