# Generated by Django 4.2a1 on 2023-04-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_alter_users_firstname_alter_users_prof_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=300, unique=True)),
                ('expiry', models.CharField(default='s', max_length=500)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
