# Generated by Django 4.2a1 on 2023-04-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_linkgenerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('token', models.CharField(max_length=50, null=True)),
                ('session_status', models.BooleanField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(null=True)),
            ],
        ),
    ]
