# Generated by Django 4.2a1 on 2023-04-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created',
        ),
        migrations.RemoveField(
            model_name='session',
            name='updated',
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_deleted',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
