# Generated by Django 4.2a1 on 2023-04-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_remove_session_created_remove_session_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
